### ISSUE TITLE
Nextcloud integration

### ISSUE THREAD

**Issue by longsleep** [strukturag/nextcloud-spreedme#36]
Similar to the Nextcloud issue https://github.com/nextcloud/server/issues/828 this issue tries to break down Nextcloud integration in work packages.
- [ ] Remove top bar, integrate call control with notifications
- [ ] Bootstrap 3 theme for buttons, headers and input which matches the Nextcloud style
- [ ] Further Nextcloud style harmonizing
- [x] Make Spreed.ME settings available as Nextcloud settings – #39
- [ ] Client and server side session resumption and keep-alive, including client-side and server-side queue
- [ ] Call resumption support after navigation (auto hold / resume)
- [ ] Web client build target to support Nextcloud without Go backend. / maybe split out the web client
- [ ] Define and implement Web client API for Nextcloud UI integration from other apps

Please comment if i missed something.

**Comment by JSoko** [comment]
Features witch would be also nice to have in Spreed.ME under Nextcloud  too:
- [x] Locking a room https://github.com/strukturag/spreed-webrtc/issues/239
- [ ] session recording https://github.com/strukturag/spreed-webrtc/issues/331
- [ ] Using Spreed Desktop for invited People who are not Nextcloud Users https://github.com/strukturag/spreed-webrtc/issues/342
- [ ] integration of sip voip https://github.com/strukturag/spreed-webrtc/issues/297

**Comment by enoch85** [comment]
- [ ] Make it possible to generate a new Shared Secret and SpreedMe WebRTC config via CLI

This is to make it possible to fully automate the install in the [Nextcloud VM](https://github.com/nextcloud/vm/blob/master/static/spreedme.sh).

**Comment by leonklingele** [comment]
We now have https://github.com/nextcloud/spreed
